#!/usr/bin/env bash
# transfers a file from a client to a server with scp

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
scp -o 0-transfer_file ubuntu@18.234.169.154


if [ "$#" -lt 3]; then
	echo "nothing used"
elif [ "$#" -lt 4]; then
	scp 